[".config/helix"]
  type = "git-repo"
  url = "git@github.com:rob-carruthers/helix.git"
  refreshPeriod = "168h"

[".local/share/icons/Memphis98"]
  type = "git-repo"
  url = "https://github.com/Stanton731/Memphis98.git"
  refreshPeriod = "168h"

[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  refreshPeriod = "168h"

[".local/share/icons/phinger-cursors-dark"]
    type = "archive"
    url = "https://github.com/phisch/phinger-cursors/releases/latest/download/phinger-cursors-variants.tar.bz2"
    include = ["./phinger-cursors-dark/**"]
    stripComponents = 2
    refreshPeriod = "168h"
