#!/bin/sh

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=16
#export LIBVA_DRIVER_NAME=nvidia
#export XDG_SESSION_TYPE=wayland
#export GBM_BACKEND=nvidia-drm
#export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1
export MOZ_USE_XINPUT2=1
export MOZ_ENABLE_WAYLAND=1
export WLR_DRM_DEVICES=/dev/dri/card0 

exec Hyprland &> /dev/null
